-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE IF NOT EXISTS public.artists
(
    artist_id integer NOT NULL,
    artist_name text COLLATE pg_catalog."default",
    CONSTRAINT artists_pkey PRIMARY KEY (artist_id)
);
CREATE TABLE IF NOT EXISTS public.genres
(
    genre_id integer NOT NULL,
    genre_name text COLLATE pg_catalog."default",
    CONSTRAINT genres_pkey PRIMARY KEY (genre_id)
);
CREATE TABLE IF NOT EXISTS public.track_artist_map
(
    track_id text COLLATE pg_catalog."default" NOT NULL,
    artist_id integer NOT NULL,
    CONSTRAINT track_artist_map_pkey PRIMARY KEY (track_id, artist_id)
);
CREATE TABLE IF NOT EXISTS public.track_genre_map
(
    track_id text COLLATE pg_catalog."default" NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT track_genre_map_pkey PRIMARY KEY (track_id, genre_id)
);
CREATE TABLE IF NOT EXISTS public.tracks
(
    track_id text COLLATE pg_catalog."default" NOT NULL,
    album_name text COLLATE pg_catalog."default",
    track_name text COLLATE pg_catalog."default",
    popularity integer,
    duration_ms integer,
    explicit boolean,
    danceability double precision,
    energy double precision,
    key integer,
    loudness double precision,
    mode integer,
    speechiness double precision,
    acousticness double precision,
    instrumentalness double precision,
    liveness double precision,
    valence double precision,
    tempo double precision,
    time_signature integer,
    CONSTRAINT tracks_pkey PRIMARY KEY (track_id)
);
ALTER TABLE IF EXISTS public.track_artist_map
    ADD CONSTRAINT track_artist_map_artist_id_fkey FOREIGN KEY (artist_id)
    REFERENCES public.artists (artist_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.track_artist_map
    ADD CONSTRAINT track_artist_map_track_id_fkey FOREIGN KEY (track_id)
    REFERENCES public.tracks (track_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.track_genre_map
    ADD CONSTRAINT track_genre_map_genre_id_fkey FOREIGN KEY (genre_id)
    REFERENCES public.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.track_genre_map
    ADD CONSTRAINT track_genre_map_track_id_fkey FOREIGN KEY (track_id)
    REFERENCES public.tracks (track_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
END;